//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spacebuilder.Ask.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spacebuilder.Ask.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 问答 的本地化字符串。
        /// </summary>
        internal static string ApplicationName_Ask {
            get {
                return ResourceManager.GetString("ApplicationName_Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您现在处于管制状态，不能问答 的本地化字符串。
        /// </summary>
        internal static string Description_ModeratedUser_CreateAnswerDenied {
            get {
                return ResourceManager.GetString("Description_ModeratedUser_CreateAnswerDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您现在处于管制状态，不能提问 的本地化字符串。
        /// </summary>
        internal static string Description_ModeratedUser_CreateQuestionDenied {
            get {
                return ResourceManager.GetString("Description_ModeratedUser_CreateQuestionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采纳回答：{0} 的本地化字符串。
        /// </summary>
        internal static string PointRecord_Pattern_AcceptedAnswer {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_AcceptedAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回答被采纳：{0} 的本地化字符串。
        /// </summary>
        internal static string PointRecord_Pattern_AnswerWereAccepted {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_AnswerWereAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 问题悬赏：{0} 的本地化字符串。
        /// </summary>
        internal static string PointRecord_Pattern_QuestionReward {
            get {
                return ResourceManager.GetString("PointRecord_Pattern_QuestionReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已解决 的本地化字符串。
        /// </summary>
        internal static string Resolved_Subject_Prefix {
            get {
                return ResourceManager.GetString("Resolved_Subject_Prefix", resourceCulture);
            }
        }
    }
}
